In [1]:
import numpy as np

In [2]:
print("Hello Kunjan")

Hello Kunjan


In [3]:
print('Hello, World!')

Hello, World!


In [4]:
arr = np.array([1,2,4,5,5])

print(arr)

print(type(arr))

[1 2 4 5 5]
<class 'numpy.ndarray'>


In [5]:
# 0-D Array

arr = np.array(42)

print(arr)

42


In [6]:
# 1-D Array

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [7]:
arr = np.array([[1, 2, 3, 4, 5],[1,2,3,4,5]])

print(arr)

print(type(arr))

print(arr.ndim)  # To find the dimension of the array

[[1 2 3 4 5]
 [1 2 3 4 5]]
<class 'numpy.ndarray'>
2


Reshape Array 

In [8]:
# Reshap From 1-D to 2-D

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

newarr = arr.reshape(4,3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [9]:
# Reshape From 1-D to 3-D

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

newarr = arr.reshape(2,3,2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [10]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

newarr = arr.reshape(3, 3)

print(newarr)


# OK Ok I Will Understand

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
# Return Copy Or View
arr = np.array([1,2,3,4,5,6,7,8])

print(arr.reshape(2,4).base)

[1 2 3 4 5 6 7 8]


In [12]:
arr = np.array([1,2,3,4,5,6,7,8])

print(arr.reshape(2,4))

[[1 2 3 4]
 [5 6 7 8]]


In [13]:
# Unknown Dimension 

arr = np.array([1,2,3,4,5,6,7,8])

newarr = arr.reshape(2,2,-1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [14]:
arr = np.array([1, 2, 3, 4, 5, 6])

# ------------------VIEW Example------------------

view_arr = arr.reshape(2,3)

print("Original Array:", arr)
print("View Array:\n", view_arr)

# show the value in view

print("\n After changing view:")
print("Original Array:", arr)
print("View Array:\n", view_arr)

#------------------Copy Example--------------------
copy_arr = arr.reshape(2,3).copy()

print("\nOriginal Array:", arr)
print("Copy Array:\n", copy_arr)

# Change the copy Value

copy_arr[0,1] = 77

print("\n After changing copy:")
print("Original Array:", arr)
print("Copy Array:\n", copy_arr)

Original Array: [1 2 3 4 5 6]
View Array:
 [[1 2 3]
 [4 5 6]]

 After changing view:
Original Array: [1 2 3 4 5 6]
View Array:
 [[1 2 3]
 [4 5 6]]

Original Array: [1 2 3 4 5 6]
Copy Array:
 [[1 2 3]
 [4 5 6]]

 After changing copy:
Original Array: [1 2 3 4 5 6]
Copy Array:
 [[ 1 77  3]
 [ 4  5  6]]


In [15]:
# Flattening the arrays

arr = np.array([[[1,2,3],[4,5,6]]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


In [16]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [17]:
arr = np.array([[1,2],[3,4]])  # Flatten (Multi-dimensional array to convert in 1D Copy Array)
new_arr = arr.flatten()
print(new_arr)

[1 2 3 4]


In [18]:
arr = np.array([[1,2],[3,4]]) # Ravel (That is given mostly View)
new_arr = arr.ravel()
print(new_arr)

[1 2 3 4]


In [19]:
arr = np.array([[1,2],[3,4]])
print(np.rot90(arr))

[[2 4]
 [1 3]]


In [20]:
# Flip(arr) 

arr = np.array([[1,2],[3,4]])  #Reverse The Array
print(np.flip(arr))

[[4 3]
 [2 1]]


In [21]:
# Fliplr(arr)

arr = np.array([[1,2],[3,4,]]) # left to Right column-wise flip
print(np.fliplr(arr))

[[2 1]
 [4 3]]


In [22]:
# flipud(arr)

arr = np.array([[1,2],[3,4]]) # Flip to Up to Down row-wise flip
print(np.flipud(arr))

[[3 4]
 [1 2]]


 NumPy Array Iterating


In [23]:
# Iterating Arrays

arr = np.array([1,2,3])

for i in arr:
    print(i)

1
2
3


In [24]:
# Iterating 2-D Arrays

arr = np.array([[1,3],[2,4]])

for i in arr:
    print(i)


[1 3]
[2 4]


In [25]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [26]:
arr = np.array([[1,2,3],[4,5,6]])

for i in arr:
    for j in i:
        print(j)

1
2
3
4
5
6


In [27]:
# Iterating 3-D Arrays

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [28]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


Iterating Arrays Using nditer()


In [29]:
# Iterating on Each Scalar Element

arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

for i in np.nditer(arr):
    print(i)

1
2
3
4
5
6
7
8


In [30]:
# Iterating Array With Different Data Types

arr = np.array([1,2,3])

for i in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
    print(i)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


In [34]:
arr = np.array([1,2,3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['f'], casting='unsafe'):
    print(x)

1.0
2.0
3.0


In [38]:
arr = np.array([1,2,3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['c'], casting='unsafe'):
    print(x)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


In [39]:
arr = np.array([1,2,3,4])

for x in np.nditer(arr, flags=['buffered'],op_dtypes=[np.complex128], casting='unsafe'):
    print(x)

(1+0j)
(2+0j)
(3+0j)
(4+0j)


In [41]:
# Iterating With Different Step Size

arr = np.array([[1,2,3,4],[5,6,7,8]])

for x in np.nditer(arr[:, ::2]):
    print(x)

1
3
5
7


In [49]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

for i in arr[::8]:
    print(i)

1
9


In [50]:
for i in arr[::-1]:
    print(i)

12
11
10
9
8
7
6
5
4
3
2
1


In [52]:
for x in np.nditer(arr[::5]):
    print(x)

1
6
11


In [53]:
for x in np.nditer(arr[::-3]):
    print(x)

3
6
9
12


In [54]:
# Enumerated Iteration Using ndenumerate()

arr = np.array([1,2,3,4])

for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0,) 1
(1,) 2
(2,) 3
(3,) 4


In [57]:
arr2 = np.array([1,2,3,4,5,6,7,8])

for idx, x in np.ndenumerate(arr2):
    print(idx, x)

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5
(5,) 6
(6,) 7
(7,) 8


In [58]:
arr3 = np.array([[1,2,3],[4,5,6]])

for idx, x in np.ndenumerate(arr3):
    print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


NumPy Joining Array


In [59]:
# Joining Numpy Arrays

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr3 = np.concatenate((arr1, arr2))
print(arr3)

[1 2 3 4 5 6]


In [60]:
arr1 = np.array([[1,2],[3,4]])

arr2 = np.array([[5,6],[7,8]])

arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
# Joining Array Using Stack Functions      (Add New axis)

arr1 = np.array([1,2,3,4])  

arr2 = np.array([5,6,7,8])

arr = np.stack((arr1, arr2), axis=1)
print(arr)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [67]:
print(type(arr))

<class 'numpy.ndarray'>


In [68]:
print(arr.ndim)

2


In [ ]:
# Stacking Along Rows       (Add in Horizontally)

arr1 = np.array([1,2,3,4])

arr2 = np.array([5,6,7,8])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6 7 8]


In [ ]:
# Stacking Along Columns        (Add in Vertically)

arr1 = np.array([1,2,3,4])  

arr2 = np.array([5,6,7,8])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
# Stacking Along Height (depth)     (Add in depth)

arr1 = np.array([1,2,3,4])  

arr2 = np.array([5,6,7,8])

arr = np.dstack((arr1, arr2))

In [75]:
print(arr)

[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]


Numpy Splitting Array

In [76]:
# Splitting Numpy Arrays    

arr = np.array([1,2,3,4,5,6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [1]:
print("hello world")

hello world


In [ ]:
print("Kunjan Patel")